repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main']
    - id: check-added-large-files
      args: ["--maxkb=2000"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ["--ignore=E501,W503"]
    entry: pflake8
    additional_dependencies: [pyproject-flake8]
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.910-1'
  hooks:
    - id: mypy