[tool.black]
line-length = 79
target-version = ['py39']

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = 79

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "format",  # handled by black
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-locals",
    "raise-missing-from",
]

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pydocstyle]
convention = "google"
match = ".*\\.py"

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
show_column_numbers = true
warn_unused_ignores = true
warn_unused_configs = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
disallow_any_unimported = true
disallow_untyped_calls = true
no_implicit_optional = true
disallow_untyped_defs = true
follow_imports = "silent"